# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Suy
tagline:             'logs'
description:         'something cool'
url:                 htts://UiyoungSeo.github.io
baseurl:             ""
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
